### PR TITLE
Added debianization

### PR DESCRIPTION
**Pull request by yma-het**
Implemented ability to pass credentions to etcd and added debianization.

### CODE REVIEW

**Comment by flaviostutz** [comment]
Oh, that was nice! Could you share in what kind of context are you using this as a Linux service?

**Comment by yma-het** [comment]
Yeah, basic node discovery service.

**Comment by flaviostutz** [comment]
> Yeah, basic node discovery service.

Nice... In which kind of system? Kubernetes? Load balancing? Cloud?...

**Comment by yma-het** [comment]
Actually, bare hardware.

**Pull request merged**
